From bugs+caf_=bugs=bugs.plt-scheme.org@plt-scheme.org Sat Mar 15 01:08:46 2014
Received: from mail-ob0-f169.google.com (mail-ob0-f169.google.com [209.85.214.169])
	by winooski.ccs.neu.edu (8.14.7/8.14.7) with ESMTP id s2F58jeh012359
	for <bugs@bugs.plt-scheme.org>; Sat, 15 Mar 2014 01:08:45 -0400
Message-Id: <201403150508.s2F58g5M012351@winooski.ccs.neu.edu>
Date: Sat, 15 Mar 2014 01:08:42 -0400
From: eric.n.dobson@gmail.com
To: bugs@racket-lang.org
Subject: delay-thread calls kill-thread without checking the preconditions

>Number:         14397
>Category:       all
>Synopsis:       delay-thread calls kill-thread without checking the preconditions
>Class:          sw-bug
>Responsible:    nobody
>Severity:       serious
>Priority:       medium
>State:          open
>Confidential:   no
>Arrival-Date:   Sat Mar 15 01:12:02 -0400 2014
>Originator:     Eric Dobson
>Organization:
plt
>Submitter-Id:   unknown
>Release:        HEAD
>Environment:
MacIntel / Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.27 Safari/537.36
>Description:
delay-thread tries to kill a thread that it doesn't completely own when an exception is raised from the thread.
>How-To-Repeat:
#lang racket
(define c1 (make-custodian))
(define c2 (make-custodian))
(parameterize ([current-custodian c2])
  (force (delay/thread
           (thread-resume (current-thread) c1)
           (error 'crash))))

; =>
exception raised by exception handler: kill-thread: the current custodian does not solely manage the specified thread
  thread: #<thread:run>; original exception raised: error: crash
error: crash
  context...:
   /Users/endobson/proj/racket/plt/racket/collects/racket/promise.rkt:119:5
   /Users/endobson/proj/racket/plt/racket/collects/racket/private/more-scheme.rkt:264:2: call-with-exception-handler
>Fix:
